context:
  initializer:
    classes:
      com.example.BeanInitializer

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: registry-server

auth-server:
  client-id: admin-cli
  client-secret: 4QbIMZEqYDVXobYsjpn5RhnEKlfnxxBU
  grant-type: client_credentials
  uri: http://localhost:8085/
  authCode: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyb3h1enU2U0lPRHpDN0hCUGh6N2FtTzdORlBPcDFPS0FvU3gzVUEtVTd3In0.eyJleHAiOjE2NzM0MDg2NTIsImlhdCI6MTY3MzM3MjY1MiwianRpIjoiYzM0NGNjMTYtNzJlYS00OTlkLWE5Y2UtNmY3NDQwMTdiMDQ4IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDg1L2F1dGgvcmVhbG1zL1NvY2lhbEFwcCIsInN1YiI6ImU4Yjc5ZTg5LTQ4NDktNGQ1OS05ZDU1LWRlYmRkZTllYzg2MiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJhZjk2ZWY5NC04MWNmLTQ4ZDctODkzMC05ZDA1NGUyY2QyOWMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiYWY5NmVmOTQtODFjZi00OGQ3LTg5MzAtOWQwNTRlMmNkMjljIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6IndpdGFzemVrOThAd3AucGwifQ.C713CygbI4dXIbqRgd8kQxJgM2HvC_PIrByYyjmFUk_InO5vw1Hkottd7baErDWIbvxKOno4B116uzg7CBk36-40sexmkHq81AJX2kbPQvzWKC6sg19J1iVPaC2gSbkh79YX2aXNyQ6WMlwxwrH-oYNPpQ0Og_PggA87cbQCMToK47j1vFuUxpRG6qhuH0N6O9aKt90nMr6Ff-j2Q-YiHY4_wD1k2rPUyiGTnFrR1KW19s0rVEnaW8tkvxrm4Lc8Q8W0YazW9IrgEanRkXFCGzNH89lvi3CekA2vSF465_lunL9bCAfPdQYmYVeEj6f8k4D_IS3I7pj0sOIOBaxZXg.eyJleHAiOjE2NzI2OTg3NjMsImlhdCI6MTY3MjY5ODQ2MywianRpIjoiODUxZDk5OTgtYzg3Mi00YjY1LWJiMGUtNjVjNDNjZTk4Y2ZhIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDg1L2F1dGgvcmVhbG1zL1NvY2lhbEFwcCIsInN1YiI6ImU4Yjc5ZTg5LTQ4NDktNGQ1OS05ZDU1LWRlYmRkZTllYzg2MiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJiMmZmNTkyNS05ZjlmLTQ5ZGQtOGIzYi04OWZlZTE5M2EwNTgiLCJhY3IiOiIxIiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiYjJmZjU5MjUtOWY5Zi00OWRkLThiM2ItODlmZWUxOTNhMDU4IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6IndpdGFzemVrOThAd3AucGwifQ.QVcaj5v0UWRvZaE0_SbHuMc1IeWvC4BiW7RoFgWK19hlIN1rRTY9RSHsujKvOUiGfSGJqzQ12Q7an32EMQH1AiBLUMZFH_JnDXqFPLWIkCxKX2smel20ExcNJrr8XRWuxr7API0RzVBoevyat2105skcwt6MvujNyikPfTlHnNG7hqHhyiWdCpxHuENjjQKcQ5eC5fXHgL6MZ9Jk1sxki3v7eHKWwuM602oNJq1TzL3JZKlWgxT-nRAI_D1jLsHX0t9xw4PTxD-6qfDF9i3xpZfWB-fYnWJ7JdpsagyTnxopAdthMYS8rJmsFXWK-nWFcYoMz4VkK0OoW89UzPhwFQ.eyJleHAiOjE2NzI2ODQwOTEsImlhdCI6MTY3MjY4Mzc5MSwianRpIjoiYjZlNjMyNzctNDU2OC00M2YwLTkxNjgtZGMwZjFhYmQyMjMyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDg1L2F1dGgvcmVhbG1zL1NvY2lhbEFwcCIsInN1YiI6ImRjYmZjZDk1LTRhZDctNDE1OC1iOWNjLTg0ZWFmMWVhYzgzZiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJjMDc5ZGI0MC1kNzcwLTRlMTQtOGMwZC0yZmViNzRkZjNhZDkiLCJhY3IiOiIxIiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiYzA3OWRiNDAtZDc3MC00ZTE0LThjMGQtMmZlYjc0ZGYzYWQ5IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsIm5hbWUiOiJEYXdpZCBXaXRhc3playIsInByZWZlcnJlZF91c2VybmFtZSI6IndpdGFzemVrOThAd3AucGwiLCJnaXZlbl9uYW1lIjoiRGF3aWQiLCJmYW1pbHlfbmFtZSI6IldpdGFzemVrIiwiZW1haWwiOiJ3aXRhc3plazk4QHdwLnBsIn0.NRSB9ykFf6bXTj1tcccJ3WVsb3EQmFiwbAoItS6DnW9K92AIMBmGghdJ25yhcARXs0O86OzbTc2z0mWjqVe3UC3w0g1IK0OwLBmORPVcU40Uxc8yDwMEWHydSKfCIm7tvA5WDxLL8D0shJCijIqnyDo2VFADOBEqOGqjK6Xl7GZYioYx65aDBMSJel9kzss5yRjj05Bu4vQYt0oydIPuAcqcrmeDnBnx3UH008xsubfh4H6YsPGq3YfGkC5byLESe8FaKcM35ba-q2u8NVUnup0U9ZuhOzVVPOKvp8ua6bU1lYZaty0g4VUx2VeDzRMeZnvhoJR26CG6f9mutYbtCw
