spring:
  config:
    import: "optional:configserver:"
  application:
    name: post-app
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/auth/realms/SocialApp
  data:
    mongodb:
      host: localhost
      database: SocialApp
      password: example
      username: root
      port: 27017
      authentication-database: admin
      uuid-representation: standard

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


auth-server:
  client-id: admin-cli
  client-secret: 4QbIMZEqYDVXobYsjpn5RhnEKlfnxxBU
  grant-type: client_credentials
  uri: http://localhost:8085/
  authCode: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyb3h1enU2U0lPRHpDN0hCUGh6N2FtTzdORlBPcDFPS0FvU3gzVUEtVTd3In0.eyJleHAiOjE2NzM0MDg2NTIsImlhdCI6MTY3MzM3MjY1MiwianRpIjoiYzM0NGNjMTYtNzJlYS00OTlkLWE5Y2UtNmY3NDQwMTdiMDQ4IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDg1L2F1dGgvcmVhbG1zL1NvY2lhbEFwcCIsInN1YiI6ImU4Yjc5ZTg5LTQ4NDktNGQ1OS05ZDU1LWRlYmRkZTllYzg2MiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJhZjk2ZWY5NC04MWNmLTQ4ZDctODkzMC05ZDA1NGUyY2QyOWMiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiYWY5NmVmOTQtODFjZi00OGQ3LTg5MzAtOWQwNTRlMmNkMjljIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6IndpdGFzemVrOThAd3AucGwifQ.C713CygbI4dXIbqRgd8kQxJgM2HvC_PIrByYyjmFUk_InO5vw1Hkottd7baErDWIbvxKOno4B116uzg7CBk36-40sexmkHq81AJX2kbPQvzWKC6sg19J1iVPaC2gSbkh79YX2aXNyQ6WMlwxwrH-oYNPpQ0Og_PggA87cbQCMToK47j1vFuUxpRG6qhuH0N6O9aKt90nMr6Ff-j2Q-YiHY4_wD1k2rPUyiGTnFrR1KW19s0rVEnaW8tkvxrm4Lc8Q8W0YazW9IrgEanRkXFCGzNH89lvi3CekA2vSF465_lunL9bCAfPdQYmYVeEj6f8k4D_IS3I7pj0sOIOBaxZXg.eyJleHAiOjE2NzMzMzMwNDAsImlhdCI6MTY3MzI5NzA0MCwianRpIjoiNGI0ZTNjM2ItNjJjNi00MmFjLWI2YWQtMGY0NDE1NzcwMzkyIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDg1L2F1dGgvcmVhbG1zL1NvY2lhbEFwcCIsInN1YiI6ImU4Yjc5ZTg5LTQ4NDktNGQ1OS05ZDU1LWRlYmRkZTllYzg2MiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiI3OWQyOGY1NS05ZGQ5LTRkM2MtYTY5YS04MTFmZDI4YjhkNjYiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiNzlkMjhmNTUtOWRkOS00ZDNjLWE2OWEtODExZmQyOGI4ZDY2IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6IndpdGFzemVrOThAd3AucGwifQ.OmFfsUNsiLxrHMWIfDxFRkwS4H1B45kOWZfIoDnD_sNxUjva4ai9BfKj9TnH92WxyAMP2euSNQpV_3M-tO3-XC3oWMaD5wTyP_Fa3XUA8utadFYtcln_yEyBaehQwRPGeLRMgWrvDTJhLX34ts1rZbxRBmCoBMUu-SlQneobgWWvAukd2qt-Xt_28iLXJ0uwVwXGmo7-1dTjUt_MxTineugtU_pADfN-vRfrstDObINKDyyrwf3rYBCXXEXgyqOgY61Y1j3O-ZlqkR0jwfUGrGdERwn9xBSEdebEK0b72FBGCX3RUTyJ7w11vt3ehiGrA_19XUZfsY_QEiXpoCpD_w
  host: http://localhost:8085/

kafka:
  bootstrapServer: localhost:9092
  topics:
    - comment-created-event
    - reply-created-event
    - comment-deleted-event
    - reply-updated-event
    - reply-deleted-event
    - group-created-event
    - group-deleted-event
    - group-profileadded-event
    - group-profileremoved-event
    - post-created-event
    - post-deleted-event
    - post-updated-event
    - post-atachementdeleted-event

management:
  endpoints:
    web:
      exposure:
        include": '*'
