spring:
  application:
    name: post-app
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/auth/realms/SocialApp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


auth-server:
  client-id: admin-cli
  client-secret: hz3dTslTMmpr5QCepUA7Dc7mIlanyt7w
  grant-type: client_credentials
  uri: http://localhost:8085/
  auth-code: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJZUl83cVpxcTJRQkNLZ1BHYjBPY1VablBGX2pCR3dZZFdIMzcxYUJUdWdjIn0.eyJleHAiOjE2Njk4ODMyMTksImlhdCI6MTY2OTg0NzIxOSwianRpIjoiZDgwZmUwZjktY2MxMy00YjBlLWEyNjctNjFlZDczM2I4MGNhIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDg1L2F1dGgvcmVhbG1zL1NvY2lhbEFwcCIsImF1ZCI6WyJyZWFsbS1tYW5hZ2VtZW50IiwiYnJva2VyIiwiYWNjb3VudCJdLCJzdWIiOiJkZGYyYjFmMC1jZmVhLTRjMTctOWI2OC0wOTQyNGI4ZTljOWEiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJhZG1pbi1jbGkiLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbImRlZmF1bHQtcm9sZXMtc29jaWFsYXBwIiwib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7InJlYWxtLW1hbmFnZW1lbnQiOnsicm9sZXMiOlsidmlldy1yZWFsbSIsInZpZXctaWRlbnRpdHktcHJvdmlkZXJzIiwibWFuYWdlLWlkZW50aXR5LXByb3ZpZGVycyIsImltcGVyc29uYXRpb24iLCJyZWFsbS1hZG1pbiIsImNyZWF0ZS1jbGllbnQiLCJtYW5hZ2UtdXNlcnMiLCJxdWVyeS1yZWFsbXMiLCJ2aWV3LWF1dGhvcml6YXRpb24iLCJxdWVyeS1jbGllbnRzIiwicXVlcnktdXNlcnMiLCJtYW5hZ2UtZXZlbnRzIiwibWFuYWdlLXJlYWxtIiwidmlldy1ldmVudHMiLCJ2aWV3LXVzZXJzIiwidmlldy1jbGllbnRzIiwibWFuYWdlLWF1dGhvcml6YXRpb24iLCJtYW5hZ2UtY2xpZW50cyIsInF1ZXJ5LWdyb3VwcyJdfSwiYWRtaW4tY2xpIjp7InJvbGVzIjpbInVtYV9wcm90ZWN0aW9uIl19LCJicm9rZXIiOnsicm9sZXMiOlsicmVhZC10b2tlbiJdfSwiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsInZpZXctYXBwbGljYXRpb25zIiwidmlldy1jb25zZW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJkZWxldGUtYWNjb3VudCIsIm1hbmFnZS1jb25zZW50Iiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJjbGllbnRJZCI6ImFkbWluLWNsaSIsImNsaWVudEhvc3QiOiIxNzIuMTguMC4xIiwicHJlZmVycmVkX3VzZXJuYW1lIjoic2VydmljZS1hY2NvdW50LWFkbWluLWNsaSIsImNsaWVudEFkZHJlc3MiOiIxNzIuMTguMC4xIn0.JItZgRkHL8cKcN6ZhqJU4mTvIeVMOCc0-Aa3h_WfKxnWhMRArwXjIXtj_4lAs6chW4H4BvVQK0yzKeBEP2qjAxFnZy0NwlmXFsatN8xCBIjqKx1QNvjBBSMG_9kzLAAcmjoVXCq3_HeWyI6irjgbFyFVlyhzEi3mALAdsu6-qTQy-j600SR6_7fvjk5F7NRjGLuEHt2Ic6tO2wfFw067_ofgauyHizJNxvKHoLcVut2Kq87NVO4iEE0pOS4DnK2Nw2cchH9Kg6dNRd-e6aoyomKYD8iy0OckGdf5KWmQDvlwfn_5N9JazrS1aFymdePDZX2BPAkCQ2Bm6eXqNFL4CA

kafka:
  bootstrapServer: localhost:9092
  topics:
    - comment-created-event
    - reply-created-event
    - comment-deleted-event
    - reply-updated-event
    - reply-deleted-event
    - group-created-event
    - group-deleted-event
    - group-profileadded-event
    - group-profileremoved-event
    - post-created-event
    - post-deleted-event
    - post-updated-event
    - post-atachementdeleted-event