context:
  initializer:
    classes:
      com.example.BeanInitializer

spring:
  config:
    import: "optional:configserver:"
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/auth/realms/SocialApp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"



server:
  port: 9090

auth-server:
  client-id: admin-cli
  client-secret: hz3dTslTMmpr5QCepUA7Dc7mIlanyt7w
  grant-type: client_credentials
  uri: http://localhost:8085/


