spring:
  config:
    import: "optional:configserver:"
  application:
    name: profile-app
  data:
    mongodb:
      host: localhost
      database: SocialApp
      password: example
      username: root
      port: 27017
      authentication-database: admin
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/auth/realms/SocialApp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

auth-server:
  client-id: admin-cli
  client-secret: 4QbIMZEqYDVXobYsjpn5RhnEKlfnxxBU
  grant-type: client_credentials
  uri: http://localhost:8085/
  authCode: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyb3h1enU2U0lPRHpDN0hCUGh6N2FtTzdORlBPcDFPS0FvU3gzVUEtVTd3In0.eyJleHAiOjE2NzMwNjcxMzIsImlhdCI6MTY3MzAzMTEzMiwianRpIjoiNDhiYmQ1ZmQtM2JkOC00MDUxLWIyNTctMjhjMWZkNzVkZGQzIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDg1L2F1dGgvcmVhbG1zL1NvY2lhbEFwcCIsInN1YiI6ImU4Yjc5ZTg5LTQ4NDktNGQ1OS05ZDU1LWRlYmRkZTllYzg2MiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJmODRlMzljYy0zZTBiLTRiM2UtYWE1YS1mNGMxM2I0ODI1MTEiLCJhY3IiOiIxIiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiZjg0ZTM5Y2MtM2UwYi00YjNlLWFhNWEtZjRjMTNiNDgyNTExIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6IndpdGFzemVrOThAd3AucGwifQ.BpilzH-XwZ51jZK98jsoUcD21oVNbzYwKOoTDDbkOrNlgZNjXxxiWi33Fe3xzvbTP4LkrIX6b3yTzcYjXHAyfaU-D1vQpC2K0GWbghxP32cRQCQeVVCOhsCfCGqntcWmsc7wtMUoDTZitWxYHTGNWsvCK5J00SVKYasRPnrImUeL8Tz62ViaDLS7Kk1C5ZOPvWqD_-YQS_byfjjGKC4ylr9ds6IdwfWa50320kzTVgkKcrbELD1waT90KCQD9_wI_Zy-KXtF8lAnDIQq7cuaFpcY7srsI5xp_oDKkljjjnksjhbNm5VnW4eryf7qUs-e4F_9MH6l2FLbFVRAvH3QWw
  host: http://localhost:8085/

kafka:
  bootstrapServer: localhost:9092
  topics:
    - profile-created-event
    - profile-updated-event
    - profile-unfolowed-event
    - profile-folowed-event
    - profile-removedfromgroup-event
    - user-updated-event
    - user-created-event
    - user-deleted-event

management:
  endpoints:
    web:
      exposure:
        include": '*'

logging:
  level:
    root: debug
    web: debug