spring:
  config:
    import: "optional:configserver:"
  application:
    name: profile-app
  data:
    mongodb:
      host: localhost
      database: SocialApp
      password: example
      username: root
      port: 27017
      authentication-database: admin
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/auth/realms/SocialApp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

auth-server:
  client-id: admin-cli
  client-secret: 4QbIMZEqYDVXobYsjpn5RhnEKlfnxxBU
  grant-type: client_credentials
  uri: http://localhost:8085/
  authCode: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyb3h1enU2U0lPRHpDN0hCUGh6N2FtTzdORlBPcDFPS0FvU3gzVUEtVTd3In0.eyJleHAiOjE2NzI5MDUyMTgsImlhdCI6MTY3Mjg2OTIxOCwianRpIjoiODFjMDVlYzEtNzJiNC00NmI0LWEyZTItMDY2ZDU3ZTAxNDc2IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDg1L2F1dGgvcmVhbG1zL1NvY2lhbEFwcCIsInN1YiI6ImU4Yjc5ZTg5LTQ4NDktNGQ1OS05ZDU1LWRlYmRkZTllYzg2MiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiJlZjhjN2MwYi0wYzNmLTQwY2MtYWEzYS1lZmYwMzhiOTI0NGQiLCJhY3IiOiIxIiwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiZWY4YzdjMGItMGMzZi00MGNjLWFhM2EtZWZmMDM4YjkyNDRkIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6IndpdGFzemVrOThAd3AucGwifQ.nM1qS-Ui5qrs3Id3UiTaL3iTT0Vfe9ko2bs_8k-AcZ7A1Ox7OL05MzLX_c24psvEB1iXFJQdVgi4OSHau9Hx7XcvZzMmc3AW8_U1NfihiTflRdT1fm0u-J7PLDP5FCGCEEke1hgQ7s0O5Ol-uFF0wnP2dcvJBiMOFmFVHpVf97AF88SW7X5q3CKa6FyJmRnrazzPdCmJgqXGAA049O9dwMDu79ovAp7Hd4KopRjJHRE_vDmMDEi6aNE-XGfzoFw0XmFCCLG0EspGGQnoguRGMiKMnO9lWdQocwegwTjcnXJn87hQIcSHVpg3NKgfYCOQZ9Ik5Mmu6vp2DadcYfcLBg
  host: http://localhost:8085/

kafka:
  bootstrapServer: localhost:9092
  topics:
    - profile-created-event
    - profile-updated-event
    - profile-unfolowed-event
    - profile-folowed-event
    - profile-removedfromgroup-event
    - user-updated-event
    - user-created-event
    - user-deleted-event

management:
  endpoints:
    web:
      exposure:
        include": '*'

logging:
  level:
    root: debug
    web: debug