spring:
  config:
    import: "optional:configserver:"
  application:
    name: profile-app
  data:
    mongodb:
      host: localhost
      database: SocialApp
      password: example
      username: root
      port: 27017
      authentication-database: admin
      uuid-representation: standard
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/auth/realms/SocialApp

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

auth-server:
  client-id: admin-cli
  client-secret: 4QbIMZEqYDVXobYsjpn5RhnEKlfnxxBU
  grant-type: client_credentials
  uri: http://localhost:8085/
  authCode: eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIyb3h1enU2U0lPRHpDN0hCUGh6N2FtTzdORlBPcDFPS0FvU3gzVUEtVTd3In0.eyJleHAiOjE2NzMwNzgzMjEsImlhdCI6MTY3MzA0MjMyMSwianRpIjoiNTdjZDkzYzMtZDkyZi00NDhmLWE0YzQtZTVhNGE2NGYzMWY0IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDg1L2F1dGgvcmVhbG1zL1NvY2lhbEFwcCIsInN1YiI6ImU4Yjc5ZTg5LTQ4NDktNGQ1OS05ZDU1LWRlYmRkZTllYzg2MiIsInR5cCI6IkJlYXJlciIsImF6cCI6ImFkbWluLWNsaSIsInNlc3Npb25fc3RhdGUiOiI1ZTZmN2FjNy0xYWE0LTRhN2MtYjVkNS0xNWJlZTdlYTVmNWYiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbIioiXSwic2NvcGUiOiJlbWFpbCBwcm9maWxlIiwic2lkIjoiNWU2ZjdhYzctMWFhNC00YTdjLWI1ZDUtMTViZWU3ZWE1ZjVmIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByZWZlcnJlZF91c2VybmFtZSI6IndpdGFzemVrOThAd3AucGwifQ.pk6y9ImFr3Dm9sg6YRKoI_1uzgUsNSJnzFOxL4v6JAWkxBfKAYARbBPEBEI66hDPaDAFDBmWyLRRi45X943iTaK1vcsNuJzagYg32F5-Wzc-eDPBF1ZRrxni6DzMN8qzVqUQHxlZWnCkYEUqpCODY9apuQP9goL1jzQHI2WZ9zYEPdFc6AiQAkfXzUl92971OmuuklMSKU78rH3BVWlt8techGzKcrDsyRNAax334xrXE8yGI2bfAPNVEFhXPwba9EB2UmELi6itAe9eYH-96TyqdqT_tv70sjmHOeT-tIQwKcq-wO6LSnGQZeeCl-mJwXqKPS6UJOrvL6TxBBKKBA
  host: http://localhost:8085/

kafka:
  bootstrapServer: localhost:9092
  topics:
    - profile-created-event
    - profile-updated-event
    - profile-unfolowed-event
    - profile-folowed-event
    - profile-removedfromgroup-event
    - user-updated-event
    - user-created-event
    - user-deleted-event

management:
  endpoints:
    web:
      exposure:
        include": '*'

logging:
  level:
    root: debug
    web: debug